#include "unity.h"
#include "unity_fixture.h"

TEST_GROUP_RUNNER(Finger)
{
	RUN_TEST_CASE(Finger, Finger_Given_RequestSetPositionState_When_UpdatePosition_Then_SettingPositionState);
	RUN_TEST_CASE(Finger, Finger_Given_RequestSetPositionStateAndIncorrectLimits_When_UpdatePosition_Then_ErrorState);
	RUN_TEST_CASE(Finger, Finger_Given_RequestSetPositionStateWithBackwardDirection_When_UpdatePosition_Then_RequiredDirectionMotionCorrect);
	RUN_TEST_CASE(Finger, Finger_Given_RequestSetPositionStateWithForwardDirection_When_UpdatePosition_Then_RequiredDirectionMotionCorrect);
	RUN_TEST_CASE(Finger, Finger_Given_SettingsPositionBackward_When_UpdatesPosition_Then_PositionSet);
	RUN_TEST_CASE(Finger, Finger_Given_SettingsPositionForward_When_UpdatesPosition_Then_PositionSet);
	RUN_TEST_CASE(Finger, Finger_Given_SettingsPositionForwardInProgress_When_UpdatesPosition_Then_SettingsPositionState);
	RUN_TEST_CASE(Finger, Finger_Given_SettingsPositionBackwardInProgress_When_UpdatesPosition_Then_SettingsPositionState);
	RUN_TEST_CASE(Finger, Finger_Given_SettingsPositionForward_When_UpdatePositionAndCurrentPositionBeyondRequired_Then_PositionSetState);
	RUN_TEST_CASE(Finger, Finger_Given_NewActuatorPosition_When_SetNewPosition_Then_SettingPositionState);
	RUN_TEST_CASE(Finger, Finger_Given_NewAnglePosition_When_SetNewAnglePosition_Then_SettingPositionState);
	RUN_TEST_CASE(Finger, Finger_Given_SettingsPositionForwardWithinDesyncronizationLimit_When_UpdatesPosition_Then_PositionSetWithoutMovement);
}